# https://github.com/anchore/syft
# https://github.com/anchore/sbom-action

name: SCA - Anchore Syft SBOM Scan

on:
  push:
    branches: [main]

env:
  imageName: "webapp01"
  tag: ${{ github.sha }}

permissions:
  contents: read
  id-token: write # required to upload artifacts

jobs:
  anchore-syft-Scan:
    name: Anchore Syft SBOM Scan

    runs-on: ubuntu-latest

    permissions:
      contents: write # required to upload to the Dependency submission API

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Build the Docker image
        run: docker build ./src/webapp01 --file ./src/webapp01/Dockerfile --tag ${{ env.imageName }}:${{ env.tag }}

      - name: Scan the image and upload dependency results
        uses: anchore/sbom-action@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0
        continue-on-error: true
        with:
          image: "${{ env.imageName }}:${{ env.tag }}"
          dependency-snapshot: true